#cloud-config

groups:
  - users
  - docker
  - sudo

users:
  - name: concierto
    gecos: Concierto Admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/sh
    homedir: /home/concierto
    groups: users, sudo, docker
    lock_passwd: true
    ssh_pwauth: false
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCSsw46VCaFaKY7BqbsIKoI31sTCeAXw5KI/ZLdQzDVuTolm9Q1ksg3RuPUA45/FbhcR0Xo4/PMj2fBDUuZJBEJKgrpGAbcVvH9ZxjYtATw1P4lhzbKxDCG14VKAO51ziX/nC5gNUAXfJNP6a51lh/KpUeXWZuonaPkfS/v4ewnB4QfmlXlOd7LnR0M7O3thR4n+SA6+LQeHjPJWqyejCzy0EALXJ+Nh4TtCLSeZtHLIq9XZChBttjJfFO5lelhbCxXDwP0Mh6FZDB6VKTZavYlM+MRDl6/h6l484DcDI2Y7XgyVzbQoAhvA1ImkMraE5fhUdvlnQ5U1M1biPM/syWGz0K+gDjO9fKgMVDT+168Mw6fZkewdQytkGX29yrmWw4o04O7PBYhMSM0P7LMfxn7SSXd4QRIzSJBmMiMjuo6jgYLZP8z2tTYQIFrUgchZKyNBksNco+YmLBzX4zi650xAk4WuVPkL7ewlDi2xZq/8j+liEu8Nbkjenp2RYfP+G0= ritchie@blackdog

runcmd:
  - [ usermod, -p, '*', concierto ]
  - [ apk , add, openssh, docker, docker-cli-compose, sudo ]
  - [ rc-update, add, docker ]
  - [ rc-update, add, sshd ]
