version: "3.7"
services:
  db:
    image: "{{services.db.image}}"
    container_name: "redis"
    environment:
      DB_PASSWORD: {{globals.DB_PASSWORD}}
    ports:
      - "{{globals.DB_PORT}}:6379"
      
  api:
    image: "{{services.api.image}}"
    container_name: "api"
    ports:
      - "8080:8080"
    env_file: 
      - api.env
    depends_on:
      - db

  balancer:
    container_name: "balancer"
    restart: always
    image: "{{services.balancer.image}}"
    env_file:
      - balancer.env
    ports:
      - "{{globals.BALANCER_PORT}}:9000"
    depends_on:
      - api
      
