#!/usr/bin/env sh

wget -q "https://github.com/babashka/babashka/releases/download/v1.3.182/babashka-1.3.182-linux-amd64-static.tar.gz" -O bb.tar.gz
tar xzf bb.tar.gz
sudo mv bb /usr/local/bin/
rm bb.tar.gz
echo "Install complete"